version: "2"
services:
  php:
    build: ./docker/php
    volumes:
      - .:/usr/share/nginx/html
  web:
    image: "nginx:1.13.8-alpine"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
    links:
      - "php"